name: Publish Package to npmjs
on:
    push:
        tags: 
            - 'v*.*.*-alpha.*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check ref
              run: |
                  REF=${{ github.ref }}
                  if [[ $REF != refs/heads/dev ]]; then
                      echo "Workflow can only run when push to dev branch and tag matches 'v*.*.*-alpha.*'"
                      exit 1
                  fi
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - uses: pnpm/action-setup@v3
              with:
                  version: 9
            - run: pnpm install
            - run: npm publish --dist-tag alpha
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
