name: Publish Package to npmjs
on:
    push:
        tags: 
            - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check branch
              run: |
                    BRANCH_NAME=${GITHUB_REF#refs/heads/}
                    if [[ "$BRANCH_NAME" != "release" ]]; then
                    echo "Workflow can only run on release branch"
                    exit 1
                    fi
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - uses: pnpm/action-setup@v3
              with:
                  version: 9
            - run: pnpm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
